name: Deploy Blazemark Blog

on:
  push:
    branches:
      - main   # 当 main 分支有更新时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. 安装依赖（如果有 requirements.txt）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      # 4. 构建 Blazemark 静态站点
      - name: Build site
        run: |
          python blazemark.py build --force

      # 5. 部署到 GitHub Pages
      - name: Deploy to Github Pages
        env:
          DEPLOY_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy site via GitHub Actions"

          # 推送到目标仓库
          git remote add origin https://x-access-token:${DEPLOY_TOKEN}@github.com/bcsm114514/bcsm114514.github.io.git
          git push -f origin main
